import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <Link className="link" href="/">
            Home
          </Link>
          <Link className="link" href="/filmography">
            Filmography
          </Link>
          <Link className="link" href="/discography">
            Discography
          </Link>
          <Link className="link" href="/Home">
            About
          </Link>
          <Link className="link" href="/Home">
            Contact Us
          </Link>
        </header>
        {children}
        <footer className="footer">Mic</footer>
      </body>
    </html>
  );
}
